server:
  port: 8085

spring:
  application:
    name: user
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${user_db}
    password: ${password_db}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s
        enabled: true
        register: true
        prefer-ip-address: true
  config:
    import: "optional:consul:"

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}

aws:
  s3:
    bucket-users: teakter-users
    region: us-east-1
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  cloudfront:
    domain:
      users: ${AWS_CLOUDFRONT_DOMAIN_USERS}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-users: teakter-users

storage:
  type: ${STORAGE_TYPE:minio}

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

#configuracion de documentacion
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /users/v3/api-docs
