networks:
  wetube-network:
    driver: bridge

services:
  # Base de Datos
  db-global:
    networks:
      - wetube-network
    image: postgres:15
    container_name: postgres-wetube
    environment:
      POSTGRES_USER: ${user_db_env}
      POSTGRES_PASSWORD: ${password_db_env}
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Consul
  consul:
    networks:
      - wetube-network
    image: hashicorp/consul:1.15
    container_name: consul-server
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

  # MinIO
  minio:
    networks:
      - wetube-network
    image: minio/minio
    container_name: minio-server
    environment:
      - MINIO_ROOT_USER=${minio_accessKey_env}
      - MINIO_ROOT_PASSWORD=${minio_secretKey_env}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  rabbitmq:
    networks:
      - wetube-network
    image: rabbitmq:3-management
    container_name: rabbitmq-wetube
    ports:
      - "5672:5672"
      - "15672:15672"

#microservicio auth
  auth-service:
    networks:
      - wetube-network
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-microservice
    depends_on:
      db-global:
        condition: service_healthy
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - user_db=${user_db_env}
      - password_db=${password_db_env}
      - JWT_SECRET=${jwt_secret_env}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-global:5432/authdb
      - SPRING_CLOUD_CONSUL_HOST=consul
      - RABBIT_HOST=rabbitmq-wetube
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest

  # microservicio video
  video-service:
    networks:
      - wetube-network
    build: 
      context: ./video
      dockerfile: Dockerfile
    container_name: video-microservice
    depends_on:
      db-global:
        condition: service_healthy
      consul:
        condition: service_started
      minio:
        condition: service_started
    environment:
      - user_db=${user_db_env}
      - password_db=${password_db_env}
      - MINIO_ACCESS_KEY=${minio_accessKey_env}
      - MINIO_SECRET_KEY=${minio_secretKey_env}
      - AWS_ACCESS_KEY=${aws_accessKey_env}
      - AWS_SECRET_KEY=${aws_secretKey_env}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-global:5432/videodb
      - SPRING_CLOUD_CONSUL_HOST=consul
      - MINIO_URL=http://minio:9000
      - STORAGE_TYPE=minio

#microservicio comments
  comments-service:
    networks:
      - wetube-network
    build:
      context: ./comments
      dockerfile: Dockerfile
    container_name: comments-microservice
    depends_on:
      db-global:
        condition: service_healthy
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - user_db=${user_db_env}
      - password_db=${password_db_env}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-global:5432/commentdb
      - SPRING_CLOUD_CONSUL_HOST=consul
      - RABBIT_HOST=rabbitmq-wetube
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest

#microservicio likes
  likes-service:
    networks:
      - wetube-network
    build:
      context: ./likes
      dockerfile: Dockerfile
    container_name: likes-microservice
    depends_on:
      db-global:
        condition: service_healthy
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - user_db=${user_db_env}
      - password_db=${password_db_env}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-global:5432/likedb
      - SPRING_CLOUD_CONSUL_HOST=consul
      - RABBIT_HOST=rabbitmq-wetube
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest

#microservice user
  user-service:
    networks:
      - wetube-network
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-microservice
    depends_on:
      db-global:
        condition: service_healthy
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - user_db=${user_db_env}
      - password_db=${password_db_env}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-global:5432/userdb
      - SPRING_CLOUD_CONSUL_HOST=consul
      - RABBIT_HOST=rabbitmq-wetube
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest

#microservicio subscription
  subscription-service:
    networks:
      - wetube-network
    build:
      context: ./subscription
      dockerfile: Dockerfile
    container_name: subscription-microservice
    depends_on:
      db-global:
        condition: service_healthy
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - user_db=${user_db_env}
      - password_db=${password_db_env}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-global:5432/subscriptiondb
      - SPRING_CLOUD_CONSUL_HOST=consul
      - RABBIT_HOST=rabbitmq-wetube
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest

  #microservicio admin
  admin-service:
    networks:
      - wetube-network
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin-microservice
    depends_on:
      db-global:
        condition: service_healthy
      consul:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - user_db=${user_db_env}
      - password_db=${password_db_env}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-global:5432/admindb
      - SPRING_CLOUD_CONSUL_HOST=consul
      - RABBIT_HOST=rabbitmq-wetube
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest

  #microservicio gateway
  gateway-service:
    networks:
      - wetube-network
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-microservice
    ports:
      - "8080:8080"
    depends_on:
      consul:
        condition: service_started
    environment:
      - JWT_SECRET=${jwt_secret_env}
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500

