spring.application.name=auth
server.port=8081

#base de datos postgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authdb}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${user_db}
spring.datasource.password=${password_db}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#visualizar las consultas sql en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

#parametros JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refreshExpiration=604800000

#configuraciones consul
spring.cloud.consul.host=${SPRING_CLOUD_CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.config.import=optional:consul:
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}

#registrar el servicio en consul automaticamente
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.loadbalancer.ribbon.enabled=false

#habilitar health check en consul apuntando al actuator
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
management.endpoint.health.show-details=always
management.endpoint.web.exposure.include=health,info

#configuraciones RabbitMQ
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}

