spring.application.name=likes
server.port=8084

#base de datos postgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/likedb}
  spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${user_db}
spring.datasource.password=${password_db}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#configuracion rabbitmq
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}

# Seguridad JWT
jwt.secret=${JWT_SECRET}

# Consul Discovery & Config
spring.cloud.consul.host=${SPRING_CLOUD_CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.config.import=optional:consul:
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.endpoint.health.show-details=always

# Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true