server:
  port: 8086

spring:
  application:
    name: admin

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/admindb}
    username: ${user_db}
    password: ${password_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s
        enabled: true
        register: true
        prefer-ip-address: true
  config:
    import: "optional:consul:"

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}

#resiliencia de servicios con resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
    instances:
      user:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      video:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

#configuracion de documentacion
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /admin/v3/api-docs

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: ALWAYS
